apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
