apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostname: my-gitlab
      containers:
      - name: gitlab
        image: gitlab/gitlab-ee
        env:
          - name: GITLAB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: gitlab-root-password
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: "/etc/gitlab"
          name: pds-config
        - mountPath: "/var/log/gitlab"
          name: pds-logs
        - mountPath: "/var/opt/gitlab"
          name: pds-data
      volumes:
      - name: pds-config
        persistentVolumeClaim:
          claimName: pvc-storage-config
      - name: pds-logs
        persistentVolumeClaim:
          claimName: pvc-storage-logs
      - name: pds-data
        persistentVolumeClaim:
          claimName: pvc-storage-data